### ISSUE TITLE
Makefile: implicit rule -> pattern rule

### ISSUE THREAD

**Issue by Rajon010** [yungyuc/insd#33]
What is discussed [here](https://yyc.solvcon.net/en/latest/nsd/01engineering/engineering.html#implicit-rule) in the tutorial is actually makefile's "[pattern rule](https://www.gnu.org/software/make/manual/make.html#Pattern-Examples)" rather than "implicit rule".
I suggest changing the section title.

**Comment by yungyuc** [comment]
@Rajon010 It is my intention to use the term "implicit rule" for the pattern rules, because the latter is a subset of the former.  It is implied in the section you quoted (https://www.gnu.org/software/make/manual/make.html#Pattern-Rules):

> You define an implicit rule by writing a pattern rule. A pattern rule looks like an ordinary rule, except that its target contains the character ‘%’ (exactly one of them).

The note is to lead readers to deep dive in the tools rather than replacing the manual.  Using a more general term makes it more informative.

I am closing the issue.  Feel free to add comments and/or reopen.
